use Linenoise;

# XXX no-op readlineint_fh op, and interactive member in MoarVM
# XXX Add Linenoise info to README
# XXX switch STDIN to blocking without linenoise patch
# XXX don't have this as a module (somehow?)
# XXX don't use builtin @COMPLETIONS
# XXX complete variables
# XXX complete loaded modules/classes/functions/etc
# XXX complete methods
# XXX this module (or whatever becomes of it) should probably just return
#     a List of completions given a line
module Completion {
    my @COMPLETIONS = <
        ANON_ENUM
        AST
        AUTOTHREAD
        AUTOTHREAD_METHOD
        Any
        Array
        Associative
        Attribute
        Backtrace
        Bag
        BagHash
        Baggy
        Blob
        Block
        Bool
        Broken
        Buf
        COMP_EXCEPTION
        CallFrame
        Callable
        Cancellation
        Capture
        Channel
        Code
        CompUnit
        CompUnitRepo
        Compiler
        Complex
        ContainerDescriptor
        Cool
        CurrentThreadScheduler
        Cursor
        DELETEKEY
        DEPRECATED
        DIVIDE_NUMBERS
        DUMP
        DYNAMIC
        Date
        DateTime
        Dateish
        Deprecation
        Distribution
        Distro
        Duration
        EAGER
        EARLIEST
        EVAL
        EXCEPTION
        EXHAUST
        EXPORTHOW
        EXPORT_SYMBOL
        Enum
        EnumMap
        Enumeration
        Exception
        Failure
        False
        FatRat
        FileChangeEvent
        FileChanged
        FileRenamed
        ForeignCode
        GATHER
        GatherIter
        Grammar
        HYPERWHATEVER
        HardRoutine
        Hash
        HashIter
        HyperWhatever
        INDIRECT_NAME_LOOKUP
        INITIALIZE_DYNAMIC
        INVOKE_KV
        IO
        Inf
        Instant
        Int
        IntAttrRef
        IntLexRef
        IntPosRef
        Iterable
        Iterator
        JSONPrettyActions
        JSONPrettyGrammar
        Junction
        Kept
        Kernel
        Label
        Less
        List
        ListIter
        LoL
        Lock
        MAIN_HELPER
        MAKE_REGEX
        METAOP_ASSIGN
        METAOP_CROSS
        METAOP_HYPER
        METAOP_HYPER_CALL
        METAOP_HYPER_POSTFIX
        METAOP_HYPER_PREFIX
        METAOP_NEGATE
        METAOP_REDUCE_CHAIN
        METAOP_REDUCE_LEFT
        METAOP_REDUCE_LIST
        METAOP_REDUCE_LISTINFIX
        METAOP_REDUCE_RIGHT
        METAOP_REDUCE_XOR
        METAOP_REVERSE
        METAOP_ZIP
        Macro
        MapIter
        Match
        Metamodel
        Method
        MethodDispatcher
        Mix
        MixHash
        Mixy
        More
        Mu
        MultiDispatcher
        NORMALIZE_ENCODING
        NOT_ALL_DEFINED_TYPE
        NQPCursorRole
        NaN
        Nil
        Num
        NumAttrRef
        NumLexRef
        NumPosRef
        Numeric
        NumericEnumeration
        OBJECT_HUH
        ORDER
        ObjAt
        Obsolete
        Order
        POSITIONS
        PROCESS
        Pair
        PairMap
        Parameter
        Parcel
        Perl
        Planned
        Pod
        Positional
        Proc
        Promise
        PromiseStatus
        Proxy
        PseudoStash
        QX
        QuantHash
        REQUIRE_IMPORT
        RWPAIR
        Range
        Rat
        Rational
        Real
        Regex
        Routine
        SEQUENCE
        SET_LEADING_DOCS
        SET_TRAILING_DOCS
        SIGABRT
        SIGALRM
        SIGBREAK
        SIGBUS
        SIGCHLD
        SIGCONT
        SIGEMT
        SIGFPE
        SIGHUP
        SIGILL
        SIGINFO
        SIGINT
        SIGIO
        SIGKILL
        SIGPIPE
        SIGPROF
        SIGPWR
        SIGQUIT
        SIGSEGV
        SIGSTKFLT
        SIGSTOP
        SIGSYS
        SIGTERM
        SIGTHR
        SIGTRAP
        SIGTSTP
        SIGTTIN
        SIGTTOU
        SIGURG
        SIGUSR1
        SIGUSR2
        SIGVTALRM
        SIGWINCH
        SIGXCPU
        SIGXFSZ
        SLICE_HUH
        SLICE_MORE_HASH
        SLICE_MORE_LIST
        SLICE_ONE_HASH
        SLICE_ONE_LIST
        Same
        Scalar
        Scheduler
        Semaphore
        Set
        SetHash
        Setty
        Signal
        Signature
        Slang
        SoftRoutine
        SprintfHandler
        Stash
        Str
        StrAttrRef
        StrDistance
        StrLexRef
        StrPosRef
        Stringy
        StringyEnumeration
        Sub
        Submethod
        Supply
        SupplyOperations
        Systemic
        THE_END
        THROW
        TRANSPOSE
        Tap
        Thread
        ThreadPoolScheduler
        True
        UInt
        UInt64
        UNBASE
        UNBASE_BRACKET
        Universal
        VAR
        VM
        Variable
        Version
        WHAT
        WINNER
        Whatever
        WhateverCode
        WrapDispatcher
        X
        abs
        acos
        acosec
        acosech
        acosh
        acotan
        acotanh
        all
        any
        array
        asec
        asech
        asin
        asinh
        atan
        atan2
        atanh
        await
        bag
        blob16
        blob32
        blob64
        blob8
        buf16
        buf32
        buf64
        buf8
        callframe
        callsame
        callwith
        cas
        categorize
        ceiling
        chars
        chdir
        chmod
        chomp
        chop
        chr
        chrs
        cis
        classify
        close
        comb
        combinations
        copy
        cos
        cosec
        cosech
        cosh
        cotan
        cotanh
        cwd
        dd
        deepmap
        defined
        die
        dir
        duckmap
        e
        elems
        end
        exit
        exp
        expmod
        fail
        first
        flat
        flatmap
        flip
        floor
        get
        getc
        gethostname
        gist
        grep
        hash
        homedir
        hyper
        i
        index
        indir
        int
        int1
        int16
        int2
        int32
        int4
        int64
        int8
        item
        join
        keys
        kv
        last
        lastcall
        lc
        lines
        link
        list
        log
        log10
        lol
        lsb
        make
        map
        max
        min
        minmax
        mix
        mkdir
        msb
        next
        nextsame
        nextwith
        none
        not
        note
        num
        num32
        num64
        on
        one
        open
        ord
        ords
        pack
        pairs
        permutations
        pi
        pick
        pipe
        pop
        print
        printf
        proceed
        prompt
        push
        rand
        redo
        reduce
        rename
        return
        reverse
        rindex
        rmdir
        roll
        roots
        rotate
        round
        roundrobin
        run
        samecase
        samewith
        say
        sec
        sech
        set
        shell
        shift
        sign
        signal
        sin
        sinh
        sleep
        slurp
        so
        sort
        splice
        split
        sprintf
        spurt
        sqrt
        squish
        srand
        start
        str
        substr
        succeed
        symlink
        take
        tan
        tanh
        tc
        tclc
        tmpdir
        trim
        truncate
        uc
        uint
        uint1
        uint16
        uint2
        uint32
        uint4
        uint64
        uint8
        undefine
        unimatch
        uniname
        uniprop
        uniq
        unique
        unival
        univals
        unlink
        unpolar
        unshift
        utf16
        utf32
        utf8
        values
        warn
        wordcase
        zip
        π
    >;

    our sub complete(Str $line, Linenoise::Completions $c) is export {
        my $m = $line ~~ /^$<prefix>=[.*?] <|w>$<last-word>=[\w*]$/;

        my $prefix    = $m ?? ~$m<prefix>    !! '';
        my $last-word = $m ?? ~$m<last-word> !! '';

        for @COMPLETIONS.grep(/^"$last-word"/) -> $completion {
            linenoiseAddCompletion($c, $prefix ~ $completion)
        }

        # XXX for debugging
        CATCH {
            default {
                say "uh-oh: $_";
            }
        }
    }
}
