#! /usr/bin/env perl
use strict;
use warnings;

use FindBin qw($Bin);

######################################################################
# This is where fudgeandrun was when it was a rakudo utility.
# It has since been recoded for implementation independence and
# moved to roast.  This stub is here to limit disruption from
# the move.
######################################################################

my $roast_far = "$Bin/spec/fudgeandrun";
-e $roast_far or
    die "fudgeandrun has moved to roast but does not seem to be there. ",
        "Perhaps updating roast (t/spec) will help.\n";

exec $^X, $roast_far, @ARGV or die "Could not exec $roast_far: $!"
    unless $^O eq 'MSWin32';
system($^X, $roast_far, @ARGV) == 0 or
    die "Could not run $roast_far: $?";

