=encoding UTF-8

=head1 release_guide.pod - guide to Rakudo releases

Rakudo's development release cycle is the Thursday following the
third Tuesday of each month (This historically allowed Rakudo to
follow Parrot's release cycle).

Each development release is given a sequential number and a code name
based on an active Perl Mongers group.  Rakudo's February 2009 release
was #14; prior releases were bundled as part of monthly Parrot releases.
For releases made so far, see the list of development releases at the
end of this document.

=head2 Planned future releases

  2015-09-17   Rakudo #91
  2015-10-22   Rakudo #92
  2015-11-19   Rakudo #93
  2015-12-17   Rakudo #94

(More planned dates can be generated with F<tools/release-dates.pl>).

=head2 Suggested .pm group names for future releases

Names can be gotten from L<http://www.pm.org> if you 
can't think of one with any particular significance to Perl 
6 or Rakudo.

=head2 Steps to create a release (for release managers)

=over 4

=item 1.

A few days before the Rakudo release, it's a good idea to...

=over 4

=item *

Remind people of the upcoming release, invite people to
update the ChangeLog file, update the ROADMAP, choose a
release name, etc.

=item *

Check if any DEPRECATED code needs to be removed because the end of the
deprecation cycle is reached.  One way of doing this, is to grep on the
YYYYMM of the release (e.g. 201412 for the 2014.12 release).  If you find
any occurrences, remove the code and make sure the spectest is still ok.

=item *

Review the RT queue for tickets that might need resolving
prior to the release, addressing them as needed.  "Tickets
that need resolving" is left your discretion.  Any problem
that has a large impact on users is worth addressing either
as a fix or as prominent documentation (the README and/or
the release announcement).

=item *

Create a draft release announcement in docs/announce/YYYY.MM.md in
markdown format.  You can often use the previous release's file as a
starting point, updating the release number, version information, name,
etc. as appropriate.

  $ git add docs/announce/YYYY.MM.md
  $ git commit docs

=item *

If it's a month relatively early in the calendar year, 
double-check that the copyright date in the README file includes 
the current year.  (It's not necessary to update copyright dates 
in other files, unless you know that a given file has been modified
in a year not reflected by the file's copyright notice.)

=back

=item 2.

Update Rakudo's leap-second tables:

  $ perl tools/update-tai-utc.pl src/core/tai-utc.pm

If a new leap second has been announced, F<tai-utc.pm> will be modified, so
commit the new version:

  $ git commit src/core/tai-utc.pm

But probably there won't be any new leap seconds, in which case the file
will be unchanged.

B<Note>: this program requires the perl modules L<Time::y2038>,
L<LWP::Simple> and L<File::Slurp> to be installed.

=item 3.

As the actual release date nears, review the git log history
to see if any additional items need to be added to the ChangeLog.
This can be conveniently done with  "git log --since=yyyy-mm-dd --reverse".

  $ git commit docs/ChangeLog

=item 4.

When it's time to cut the release, finalize the new release 
announcement in docs/announce/YYYY.MM.md .  (If one hasn't already
been created, see step 1 above.) Highlight areas in which the 
new release is significant.  If possible, also give some small 
details about the choice of release name.  (If the details 
are a bit lengthy, this can often best be done as a separate
section at the bottom of the announcement.)

Include a list of contributors since the last release in the announcement.
You can get an automatically generated list by running

  $ perl6 tools/contributors.pl6

Please check the result manually for duplicates and other errors.

  $ git add docs/announce/YYYY.MM.md
  $ git commit docs

=item 5.

Update the release dates and names at the bottom of this file
(F<docs/release_guide.pod>).  Also improve these instructions if
you find any steps that are missing.

  $ git commit docs/release_guide.pod

=item 6.

Create an NQP release with the same C<YYYY.MM> version number
as Rakudo. Follow NQP's C<docs/release_guide.pod> file to do that.

=item 7.

Go back to the Rakudo repository, and update the NQP dependency:

  $ echo YYYY.MM > tools/build/NQP_REVISION
  $ git commit -m '[release] bump NQP revision' tools/build/NQP_REVISION

=item 8.

Enter the new version into the F<VERSION> file, and commit the changes:

  $ echo YYYY.MM > VERSION
  $ git commit -m '[release] bump VERSION' VERSION

=item 9.

Make sure any locally modified files have been pushed back to github.

  $ git status
  $ git push

=item 10.

Make sure everything compiles and runs from a known clean state:

  $ make realclean
  $ perl Configure.pl --gen-moar --backends=ALL
  $ make
  $ make test
  $ make stresstest

There are many tests to run for the stresstest target.  If
you have a machine with multiple CPU cores, you may want to
execute that last as

  $ TEST_JOBS=4 make stresstest

where 4 is the number of CPU cores.  This should make the
total time to execute all of the tests dramatically less.

Continue adjusting things until make stresstest passes as expected.
Often this means fixing a bug, fudging a test, or (temporarily?)
commenting out a test file in t/spectest.data .  Use your best
judgment or ask others if uncertain what to do here.

=item 11.

Create a tarball by entering C<make release VERSION=YYYY.MM>,
where YYYY.MM is the month for which the release is being made.
This will create a tarball file named C<rakudo-YYYY.MM.tar.gz>.

B<Caution>: this step removes any untracked files in F<t/spec>.
So please make a backup if you have any important data in there.

=item 12.

Unpack the tar file into another area, and test that it
builds and runs properly using the same process in step 10.
If there are any problems, fix them and go back to step 10.

=item 13.

Tag the release by its release month ("YYYY.MM") and its code name.

  $ git tag -s -a -m"tag release #nn" YYYY.MM    # e.g., 2013.08
  $ git tag -s -a -m"tag release #nn" CODENAME   # e.g., "Bratislava"
  $ git push --tags

The C<-s> tells git to sign the release with your PGP/GPG key, so it will
likely ask you for the passphrase of your secrect key.

If you have no PGP key, you might need to
L<create one first|https://fedoraproject.org/wiki/Creating_GPG_Keys>. Should
that prove impossible, you can omit the C<-s> from the command line.

=item 14.

Sign the tarball with your PGP key:

    $ gpg -b --armor rakudo-YYYY-MM.tar.gz

=item 15.

Upload the tarball and the signature to L<http://rakudo.org/downloads/rakudo>:

  $ scp rakudo-YYYY.MM.tar.gz rakudo-YYY-MM.tar.gz.asc \
       rakudo@rakudo.org:public_html/downloads/rakudo/

If you do not have permissions for that, ask one of (pmichaud, jnthn, FROGGS,
masak, tadzik, moritz, PerlJam,  [Coke], lizmat, timotimo, fsergot)) on #perl6 to do it for you.

=item 16.

To avoid public confusion with Rakudo Star releases, we now publish 
compiler release announcements ONLY to perl6-compiler@perl.org.  
(We may restart widespread announcements of compiler releases 
once they are known, or we may begin publishing a single
announcement for both.)

Don't send out any announcements until the files are actually available
per step 14 above.

=item 17.

Update the Wikipedia entry at L<http://en.wikipedia.org/wiki/Rakudo>.

=item 18.

You're done!  Celebrate with the appropriate amount of fun.

=back

=head2 Development releases so far

  2009-02-26   Rakudo #14 "Vienna"             (pmichaud)
  2009-03-20   Rakudo #15 "Oslo"               (pmichaud)
  2009-04-23   Rakudo #16 "Bratislava"         (pmichaud)
  2009-05-21   Rakudo #17 "Stockholm"          (pmichaud)
  2009-06-18   Rakudo #18 "Pittsburgh"         (pmichaud)
  2009-07-23   Rakudo #19 "Chicago"            (moritz)
  2009-08-20   Rakudo #20 "PDX"                (kyle)
  2009-09-17   Rakudo #21 "Seattle"            (particle)
  2009-10-22   Rakudo #22 "Thousand Oaks"      (duff)
  2009-11-19   Rakudo #23 "Lisbon"             (masak)
  2009-12-17   Rakudo #24 "Seoul"              (chromatic)
  2010-01-22   Rakudo #25 "Minneapolis"        (pmichaud)
  2010-02-18   Rakudo #26 "Amsterdam"          (mberends)
  2010-03-18   Rakudo #27 "Copenhagen"         (smash)
  2010-04-22   Rakudo #28 "Moscow"             (moritz)
  2010-05-20   Rakudo #29 "Erlangen"           (colomon)
  2010-06-17   Rakudo #30 "Kiev"               (masak)
  2010-07-22   Rakudo #31 "Atlanta"            (Coke)
  2010-08-19   Rakudo #32 "Pisa"               (mathw)
  2010-09-23   Rakudo #33 "Milan"              (moritz)
  2010-10-21   Rakudo #34 "Paris"              (duff)
  2010-11-18   Rakudo #35 "Melbourne"          (masak)
  2010-12-23   Rakudo #36 "New York"           (smash)
  2011-01-20   Rakudo #37 "BristolBath"        (tadzik)
  2011-02-17   Rakudo #38 "Toulouse"           (arnsholt)
  2011-03-17   Rakudo #39 "Orlando"            (jdhore)
  2011-04-21   Rakudo #40 "ZA"                 (duff)
  2011-05-19   Rakudo #41 "Dahut"              (jdhore)
  2011-06-23   Rakudo #42 "Bruxelles"          (jdhore)
  2011-07-21   Rakudo #43 "Beijing"            (mberends,moritz)
  2011-08-18    -- none --
  2011-09-30   Rakudo #44 "Riga"               (tadzik)
  2011-10-20   Rakudo #45 "Houston"            (duff)
  2011-11-17   Rakudo #46 "London"             (tadzik)
  2011-12-22   Rakudo #47 "Columbus"           (moritz)
  2012-01-23   Rakudo #48 "Toronto"            (moritz)
  2012-02-23   Rakudo #49 "SPb"                (masak)
  2012-03-22   Rakudo #50 "Argentina"          (masak)
  2012-04-19   Rakudo #51 "Brazos Valley"      (Coke)
  2012-04-25   2012.04.1                       (moritz)
  2012-05-17   Rakudo #52 "MadMongers"         (tadzik)
  2012-06-21   Rakudo #53 "Strasbourg"         (duff)
  2012-07-19   Rakudo #54 "Tallinn"            (masak)
  2012-08-23   Rakudo #55 "Frankfurt"          (tadzik,moritz)
  2012-09-20   Rakudo #56 "Perl"               (masak)
  2012-09-29   2012.09.1                       (pmichaud)
  2012-10-18   Rakudo #57 "Tokyo"              (duff)
  2012-11-22   Rakudo #58 "Walnut"             (FROGGS)
  2012-12-20   Rakudo #59 "Warszawa"           (masak)
  2013-01-17   Rakudo #60 "Sonoma"             (isBEKaml)
  2013-02-21   Rakudo #61 "drinkers"           (tadzik)
  2013-02-23   2013.02.1                       (moritz)
  2013-03-21   Rakudo #62 "Singapore"          (masak)
  2013-04-18   Rakudo #63 "Albany"             (Coke)
  2013-05-23   Rakudo #64 "Austin"             (FROGGS)
  2013-06-20   Rakudo #65 "Poznan"             (masak)
  2013-07-18   Rakudo #66 "Edinburgh"          (moritz,lizmat)
  2013-08-22   Rakudo #67 "Bicycle"            (moritz)
  2013-09-19   Rakudo #68 "Shanghai"           (masak)
  2013-10-17   Rakudo #69 "Roederbergweg"      (Coke)
  2013-11-21   Rakudo #70 "Malmö"              (lizmat)
  2013-12-19   Rakudo #71 "Advent"             (moritz)
  2014-01-23   Rakudo #72 "Plano"              (masak)
  2014-02-20   Rakudo #73 "Karlsruhe"          (timotimo)
  2014-03-20   Rakudo #74 "Adelaide"           (tadzik)
  2014-04-17   Rakudo #75 "Echt"               (masak)
  2014-05-22   Rakudo #76 "Bajor"              (FROGGS)
  2014-06-19   Rakudo #77 "Gdańsk"             (sergot)
  2014-07-17   Rakudo #78 "Sofia"              (FROGGS)
  2014-08-21   Rakudo #79 "Minsk"              (Coke)
  2014-09-18   Rakudo #80 "HongKong"           (masak)
  2014-10-23   Rakudo #81 "Linz"               (duff)
  2014-11-20   Rakudo #82 "Helsinki"           (lizmat)
  2014-12-18   Rakudo #83 "Cologne"            (lizmat)
  2014-12-19   2014.12.1                       (lizmat)
  2015-01-22   Rakudo #84 "Gotanda"            (Coke)
  2015-02-19   Rakudo #85 "Berlin"             (lizmat)
  2015-03-19   Rakudo #86 "Cluj"               (FROGGS)
  2015-04-23   Rakudo #87 "Vladivostok"        (masak)
  2015-05-21   Rakudo #88 "Dresden"            (FROGGS)
  2015-06-18   Rakudo #89 "Salt Lake"          (hoelzro)
  2015-07-24   Rakudo #90 "Prague"             (masak)
  2015-07-24   2015.07.1                       (masak)
  2015-07-25   2015.07.2                       (moritz)

=head1 COPYRIGHT

Copyright (C) 2009-2015, The Perl Foundation.

=cut

# Local Variables:
# fill-column: 100
# End:
# vim: expandtab shiftwidth=4:
